<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-03-28T14:24:47Z" name="Default suite" finished-at="2018-03-28T14:25:07Z" duration-ms="20024">
    <groups>
      <group name="titleTest">
        <method signature="GoogleTest.titleTest()[pri:0, instance:com.Sessions.GoogleTest@38e79ae3]" name="titleTest" class="com.Sessions.GoogleTest"/>
      </group> <!-- titleTest -->
    </groups>
    <test started-at="2018-03-28T14:24:47Z" name="Default test" finished-at="2018-03-28T14:25:07Z" duration-ms="20024">
      <class name="com.Sessions.GoogleTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.Sessions.GoogleTest@38e79ae3]" started-at="2018-03-28T14:24:47Z" name="setUp" finished-at="2018-03-28T14:25:06Z" duration-ms="18935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="titleTest()[pri:0, instance:com.Sessions.GoogleTest@38e79ae3]" started-at="2018-03-28T14:25:06Z" name="titleTest" finished-at="2018-03-28T14:25:06Z" duration-ms="18" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fuck off expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fuck off expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.Sessions.GoogleTest.titleTest(GoogleTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest -->
        <test-method is-config="true" signature="tearUp()[pri:0, instance:com.Sessions.GoogleTest@38e79ae3]" started-at="2018-03-28T14:25:06Z" name="tearUp" finished-at="2018-03-28T14:25:07Z" duration-ms="1049" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
      </class> <!-- com.Sessions.GoogleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
